### PR TITLE
PLNSRVCE-693: remove .git suffix from component repo URL

### PR DESCRIPTION
**Pull request by tkdchen**
Signed-off-by: Chenxiong Qi <cqi@redhat.com>

### CODE REVIEW

**Review by Michkov — APPROVED** [review]

**Comment by tkdchen** [comment]
Reproduce with this helper diff:

```diff
diff --git a/hack/build/build-via-appstudio.sh b/hack/build/build-via-appstudio.sh
index 85bf0ac..d8ea4bf 100755
--- a/hack/build/build-via-appstudio.sh
+++ b/hack/build/build-via-appstudio.sh
@@ -35,7 +35,8 @@ fi
 
 function create-component {
   GIT_URL=$1
-  NAME=$(echo $GIT_URL | grep -o '[^/]*$')
+  REPO=$(echo $GIT_URL | grep -o '[^/]*$')
+  NAME=${REPO%%.git}
   IMAGE=quay.io/$MY_QUAY_USER/$NAME
   oc delete --ignore-not-found component $NAME
   yq e "(.metadata.name=\"$NAME\") | (.spec.componentName=\"$NAME\") | (.spec.source.git.url=\"$GIT_URL\") | (.spec.containerImage=\"$IMAGE\") | (.metadata.annotations.pipelinesascode=\"$PIPELINESASCODE\")" $SCRIPTDIR/templates/component.yaml | oc apply -f-
```

It ensures the component name is set correctly, but `.spec.source.git.url` is set with a URL which has suffix `.git`.

**Comment by psturc** [comment]
```
Error: stat /tmp/tmp.r8zxbRNJM2/hack/../components/build/build-service/kustomization.yaml: no such file or directory
Error: error when bootstrapping cluster: reached maximum number of attempts (2). error: running "./scripts/install-appstudio.sh " failed with exit code 1
```
should be fixed with [this PR](https://github.com/redhat-appstudio/infra-deployments/pull/973/files)

/test build-service-e2e

**Comment by psturc** [comment]
@tkdchen we could probably test this change by updating[ component url in e2e-tests repo](https://github.com/redhat-appstudio/e2e-tests/blob/78b26e342045b1312d5cb251dfa601c5c4b6cb4c/tests/build/build.go#L31)

would you be ok with updating the test?

if you create a PR from the same branch name in e2e-tests repo (i.e. `PLNSRVCE-693-work-with-url.git`), then the change will get picked up and tested in CI automatically from this PR.

**Comment by tkdchen** [comment]
Please hold on merging this pr. I'm trying another solution. 

> would you be ok with updating the test?

@psturc Sure. The new attempt will happen in application-service. Does it also work by creating pr from same branch name in e2e-tests?

**Comment by psturc** [comment]
> Please hold on merging this pr. I'm trying another solution.
> 
> > would you be ok with updating the test?
> 
> @psturc Sure. The new attempt will happen in application-service. Does it also work by creating pr from same branch name in e2e-tests as the one in application-service repo?

yes afaik the PR pairing should work from application-service repo as well

**Comment by tkdchen** [comment]
Hi, PTAL.

**Review by Michkov — APPROVED** [review]

**Pull request merged**
