### PR TITLE
PLNSRVCE-910: remove registry-auth from build-service

### PR DESCRIPTION
**Pull request by tkdchen**
Signed-off-by: Chenxiong Qi <cqi@redhat.com>

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Comment by psturc** [comment]
this change requires an update to [e2e-tests](https://github.com/redhat-appstudio/e2e-tests/blob/63f99d281bbf6cd54e7dece553ac924729cee0d8/tests/build/build.go#L798). @tkdchen would you mind creating a PR with that change and try to pair it with this PR?

**Comment by tkdchen** [comment]
> this change requires an update to [e2e-tests](https://github.com/redhat-appstudio/e2e-tests/blob/63f99d281bbf6cd54e7dece553ac924729cee0d8/tests/build/build.go#L798). @tkdchen would you mind creating a PR with that change and try to pair it with this PR?

@psturc Update of e2e-tests is part of PLNSRVCE-910. There will be pr for it.

**Comment by Michkov** [comment]
Removed in https://github.com/redhat-appstudio/build-service/pull/102

**Pull request closed without merging**
